#!/bin/sh
# Conectiva Linux

# these files are left sitting around by TheNextLevel.
rm -f $HOME/Xrootenv.0
rm -f /tmp/fvwmrc* 2>/dev/null

/usr/X11R7/bin/xmodmap $(/etc/X11/setxmodmap)

# First thing - check the user preferences
if [ -f $HOME/.wm_style ] ; then
    WMSTYLE=`cat $HOME/.wm_style`
    case "$WMSTYLE" in 
	Afterstep | AfterStep)
	    exec afterstep
	    ;;
	WindowMaker | Windowmaker | WMaker |  wmaker)
	    exec windowmaker
	    ;;
	Fvwm95 | fvwm95)
	    exec fvwm95
	    ;;
	Mwm | MWM | Lesstif)
	    exec fvwmmwm
	    ;;
	icewm | IceWm | IceWM)
	    exec icewm
	    ;;
	blackbox | Blackbox | BlackBox)
	    exec blackbox
	    ;;
        xfce | XFce )
            exec xfce
            ;;
	Kde | kde | KDE)
		if [ -f /usr/bin/startkde ]; then
			exec /usr/bin/startkde
		elif [ -f /opt/kde/bin/startkde ]; then
			exec /opt/kde/bin/startkde
		fi
		;;
	cinnamon | Cinnamon | CINNAMON)
		if [ -f /usr/bin/cinnamon-session ]; then
			exec /usr/bin/cinnamon-session
		fi
		;;
	mate | Mate | MATE)
		if [ -f /usr/bin/mate-session ]; then
			exec /usr/bin/mate-session
		fi
		;;
	gnome | Gnome | GNOME)
		if [ -f /usr/bin/gnome-session ]; then
			exec /usr/bin/gnome-session
		fi
		;;
	e | enlightenment)
		exec enlightenment
		;;
	qvwm | Qvwm | QVWM)
		exec qvwm
		;;
    esac
fi

# check to see if the _system_ has a preferred desktop
PREFERRED=
if [ -f /etc/defaults/desktop ]; then
    PREFERRED=`cat /etc/defaults/desktop`
    case $PREFERRED in
    MATE | mate)
	PREFERRED=mate-session
    ;;
    GNOME | gnome)
	PREFERRED=gnome-session
    ;;
    KDE | kde)
	PREFERRED=gnome-session
    ;;
    esac
fi

if [ -n "$PREFERRED" ] && \
	which $PREFERRED >/dev/null 2>&1; then
    PREFERRED=`which $PREFERRED`
    exec $PREFERRED
fi

# Default: WindowMaker
windowmaker || {
    # gosh, neither fvwm95 nor fvwm2 is available;
    # let's try regular fvwm (AnotherLevel doesn't work with fvwm1).
    if [ -n "$(type -path fvwm)" ]; then
	# if this works, we stop here
	exec fvwm
    fi

    # wow, fvwm isn't here either ... 
    # use twm as a last resort.
    xterm &
    exec twm
}

