# $NetBSD$

PKGNAME=        ${PYPKGPREFIX}-socks
DISTNAME=	SocksiPy-branch-1.01
CATEGORIES=     lzt
MASTER_SITES=	${MASTER_SITE_PYPI:=S/SocksiPy-branch/}

MAINTAINER=     kethzer.dr@gmail.com
HOMEPAGE=	https://files.pythonhosted.org/packages/source/S/SocksiPy-branch/
COMMENT=        Python SOCKS module
LICENSE=        modified-bsd

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
