# $NetBSD$

PKGNAME=        ${PYPKGPREFIX}-ptyprocess-0.5.1
DISTNAME=	ptyprocess-0.5.1
CATEGORIES=	lzt
MASTER_SITES=	https://pypi.python.org/packages/source/p/ptyprocess/

MAINTAINER=	nervoso@k1.com.br
HOMEPAGE=	https://pypi.python.org/packages/source/p/ptyprocess/
COMMENT=	python pty process

USE_LANGUAGES=	# none

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
